Square per digit
bellshade/Typescript pull request #11
Opened 2021-10-03 17:49 UTC by Rakhmadi

2021-10-04 08:47 UTC, AlfatArdiansa commented on TSExample/exesAndOhs.ts
> +// xAndO("zzoo") => false
Commentnya coba di ganti jadi multi line biar gk kebanyakan "//"
Contohnya
```ts
/*
Comment
Multi Line
*/
```

2021-10-04 08:49 UTC, AlfatArdiansa commented on TSExample/squareEveryDigits.ts
> +// output : 6^2,1^2,6^2,2^2 => '36','1','36','4' => 361364
Gunakan multi line comment

2021-10-04 08:52 UTC, AlfatArdiansa requested changes
Gunakan multi line comment biar gk kebanyakan double slash(//)

2021-10-05 09:50 UTC, AlfatArdiansa approved these changes
LGTM. 👏

2021-10-05 10:06 UTC, nomadkode approved these changes
dokumentasi aman, LGTM 👍🏼

2021-10-05 11:25 UTC, AlfatArdiansa commented
Thank you untuk partisipasinya mengajarkan teman-teman Programmer pemula 😄

2021-10-05 11:26 UTC, merged