Add: Function
bellshade/Typescript pull request #12
Opened 2021-10-03 17:52 UTC by Iqbaladudu

Contoh kode untuk implementasi fungsi di Typescript, contoh-contoh tersebut mencakup:

- Anotasi tipe data di dalam parameter fungsi
- Anotasi tipe data untuk nilai kembalian(return)

2021-10-04 08:41 UTC, AlfatArdiansa commented on Function/function.ts
> +Parameter yang dimasukkan hatus memiliki tipe data yang sama dengan argumen fungsi di atas
Typo

2021-10-04 08:43 UTC, AlfatArdiansa commented on Function/function.ts
> +Di dalam Typescript, kita bisa menentukan tipe data tertentu untuk nilai kembalian(return) fungsi, fitur ini juga dikenal dengan Return Type Annotations, anotasi tipe data tersebut bisa kita tambahka
Dibuat jadi 2 baris biar pembaca gk perlu scroll kanan kiri

2021-10-04 08:44 UTC, AlfatArdiansa requested changes
Masih ada Typo sama sedikit perbaikan coba di revisi dulu :)

2021-10-04 09:40 UTC, AlfatArdiansa approved these changes
Good job. Thank you untuk partisipasinya untuk membantu mengajarkan teman programmer pemula 🚀

2021-10-04 09:40 UTC, Iqbaladudu commented
> Masih ada Typo sama sedikit perbaikan coba di revisi dulu :)

Siap, terimakasih Bang

2021-10-04 09:41 UTC, merged

2021-10-04 09:41 UTC, Iqbaladudu commented
> Good job. Thank you untuk partisipasinya untuk membantu mengajarkan teman programmer pemula rocket

Sama-sama Bang. Semoga sukses selalu. Aamiin.

2021-10-05 05:55 UTC, nomadkode reviewed
terima kasih @Iqbaladudu sudah berkontribusi di bellshade. 😄