add: menambahkan file arrayTupple.ts
bellshade/Typescript pull request #9
Opened 2021-10-03 14:12 UTC by ezza022

2021-10-04 09:00 UTC, AlfatArdiansa requested changes
Tolong di ubah pake comment multi line jangan pake TSDoc
Contoh:
```ts
/*
Comment
Multi Line
*/

/**
* TSDoc / JSDoc
*/
```

Soalnya usecasenya berbeda comment untuk mengkomentari sedangkan TSDoc/JSDoc untuk ngasih tahu IDE/Code Editor Tipe Data atau bentuk data apa yang diinginkan seorang programmer

2021-10-04 10:00 UTC, AlfatArdiansa commented
Jadiin satu aja om commentnya kan gk ada kodingan

2021-10-04 10:05 UTC, ezza022 commented
> Jadiin satu aja om commentnya kan gk ada kodingan

ohiya sorry

2021-10-04 10:32 UTC, AlfatArdiansa approved these changes
Good Job. Thank you untuk partisipasinya mengajarkan teman-teman programmer pemula 👏

2021-10-04 10:32 UTC, merged

2021-10-05 05:56 UTC, nomadkode reviewed
terima kasih @ezza022 sudah berkontribusi di bellshade. 😄